--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/endeavouros/backgrounds/eos_wallpapers_community/neon_astronaut_endeavor.jpg"

-- Special
background="#090713"
foreground="#e8c7e7"
cursor="#e8c7e7"

-- Colors
color0="#090713"
color1="#d9274b"
color2="#5f22c3"
color3="#c42ad9"
color4="#cb31da"
color5="#5adde2"
color6="#cd59e1"
color7="#e8c7e7"
color8="#a28ba1"
color9="#d9274b"
color10="#5f22c3"
color11="#c42ad9"
color12="#cb31da"
color13="#5adde2"
color14="#cd59e1"
color15="#e8c7e7"
